site_name: Data Science Unit
site_description: Todo
site_url: ""
docs_dir: content
site_dir: docs
use_directory_urls: false

theme:
  name: materialx
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy
  topbar_style: primary   # glass primary accent
  palette:
    - scheme: default
      primary: blue
      accent: lightblue

nav:
  - Home: index.md
  - What we do: whatwedo.md
  - Our principles: principles.md
  - Showroom: showroom.md
  - Contact: contact.md

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - tables
  - toc:
      permalink: true

extra_css:
  - stylesheets/extra.css