site_name: Data Science Unit
site_description: Todo
site_url: ""
docs_dir: content
site_dir: docs
use_directory_urls: false

theme:
  name: materialx
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy
  topbar_style: primary   # glass primary accent
  palette:
    - scheme: default
      primary: blue
      accent: lightblue

nav:
  - Home: index.md
  - Showroom: showroom.md
  - Contact: contact.md

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
